name: CD

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MYFITFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYFITFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYFITFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: myfit.azurecr.io
          registryUsername: ${{ secrets.MYFITFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYFITFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: myfit-frontend
          resourceGroup: MyFit
          imageToBuild: myfit.azurecr.io/myfit-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


